---
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
extends:
- airbnb-base
- plugin:react/recommended
- plugin:jest/recommended
- prettier
- prettier/react
plugins:
- import
- jest
- jsx-a11y
- prettier
- react
env:
  es6: true
  browser: true
  jest: true
  node: true
rules:
  import/no-extraneous-dependencies: 0
  prettier/prettier:
  - error
  - trailingComma: es5
    singleQuote: true
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/valid-expect: error
  no-underscore-dangle: 0
  prefer-destructuring: 0
  react/display-name: 0
  no-undef: 0
settings:
  import/resolver:
    babel-module: {}
