export const UPDATE_QUERY = 'UPDATE_QUERY';
export const RESET_QUERY = 'RESET_QUERY';
export const UPDATE_RESULTS = 'UPDATE_RESULTS';
export const RESET_RESULTS = 'RESET_RESULTS';
export const SELECT_NEXT_ITEM = 'SELECT_NEXT_ITEM';
export const SELECT_PREVIOUS_ITEM = 'SELECT_PREVIOUS_ITEM';
export const RESET_SELECTED_ITEM = 'RESET_SELECTED_ITEM';
export const SET_THEME = 'SET_THEME';
