export const UPDATE_RESULTS = 'UPDATE_RESULTS';
export const RESET_RESULTS = 'RESET_RESULTS';
export const SELECT_ITEM = 'SELECT_ITEM';
export const SELECT_NEXT_ITEM = 'SELECT_NEXT_ITEM';
export const SELECT_PREVIOUS_ITEM = 'SELECT_PREVIOUS_ITEM';
export const RESET_SELECTED_ITEM = 'RESET_SELECTED_ITEM';
